#!/bin/bash

SRCDIR=~/src/linux
cd $SRCDIR/drivers

TARGET=v4.10

git checkout -fq $TARGET
for d in $(find ~/src/linux/drivers/ -maxdepth 1 -type d | sed -e '/.*drivers\/$/d' | sort) ; do
    echo -ne "$(basename $d)\t"
    echo "$(find $d -type f -name '*.[chS]' -exec wc -l {} \; | awk 'BEGIN{sum=0}{sum+=$1}END{print sum}')"
done | sort -nr -k2
