#!/bin/bash

OLDVERSION=v4.0

while read VERSION ; do
    echo -ne "${VERSION}\t"
    git log --oneline ${OLDVERSION}..${VERSION} | wc -l
    OLDVERSION=$VERSION
done <~/practice/kernel_scale/rc_patches.src
