#!/bin/bash

SRCDIR=~/src/linux

cd $SRCDIR

for ((i=12;i<=39;i++)) ; do
    LATEST=$(git tag | sed -n -e "s/v2\.6\.$i\.\([0-9]*\)$/\1/p" | sort -nr | head -1)
    echo -ne "v2.6.$i\t"
    git checkout -fq v2.6.$i.$LATEST
    find -type f -name '*.[chS]' -exec wc -l {} \; | awk 'BEGIN{sum=0}{sum+=$1}END{print sum}'
done

for ((i=0;i<=19;i++)) ; do
    LATEST=$(git tag | sed -n -e "s/v3\.$i\.\([0-9]*\)$/\1/p" | sort -nr | head -1)
    echo -ne "v3.$i\t"
    git checkout -fq v3.$i.$LATEST
    find -type f -name '*.[chS]' -exec wc -l {} \; | awk 'BEGIN{sum=0}{sum+=$1}END{print sum}'
done

for ((i=0;i<=10;i++)) ; do
    LATEST=$(git tag | sed -n -e "s/v4\.$i\.\([0-9]*\)$/\1/p" | sort -nr | head -1)
    echo -ne "v4.$i\t"
    git checkout -fq v4.$i.$LATEST
    find -type f -name '*.[chS]' -exec wc -l {} \; | awk 'BEGIN{sum=0}{sum+=$1}END{print sum}'
done
