#!/bin/bash

SRCDIR=~/src/linux

cd $SRCDIR

for ((i=12;i<=39;i++)) ; do
    git checkout -fq v2.6.$i
    find -type f -name '*.[chS]' -exec wc -l {} \; | awk 'BEGIN{sum=0}{sum+=$1}END{print sum}'
done

for ((i=0;i<=19;i++)) ; do
    git checkout -fq v3.$i
    find -type f -name '*.[chS]' -exec wc -l {} \; | awk 'BEGIN{sum=0}{sum+=$1}END{print sum}'
done

for ((i=0;i<=10;i++)) ; do
    git checkout -fq v4.$i
    find -type f -name '*.[chS]' -exec wc -l {} \; | awk 'BEGIN{sum=0}{sum+=$1}END{print sum}'
done
