#!/bin/bash

SRCDIR=~/src/linux

cd $SRCDIR

for ((i=12;i<=39;i++)) ; do
    git log --oneline v2.6.$(($i-1))..v2.6.$i | wc -l
done

git log --oneline v2.6.39..v3.0 | wc -l

for ((i=1;i<=19;i++)) ; do
    git log --oneline v3.$(($i-1))..v3.$i | wc -l
done

git log --oneline v3.19..v4.0 | wc -l

for ((i=1;i<=10;i++)) ; do
    git log --oneline v4.$(($i-1))..v4.$i | wc -l
done
